/**
 * @interface Position
 * @description Represents a single position (role) within the organizational chart,
 * including both structural and financial data.
 */
export interface Position {
  /** Unique identifier for the position. */
  id: string;
  /** The title of the role (e.g., "Software Engineer", "Marketing Manager"). */
  role: string;
  /** The annual salary for this position. */
  salary: number;
  /** The hourly billable rate for this position, if applicable. */
  rate: number;
  /** The percentage of time this position is expected to be utilized (billable). */
  utilization: number;
  /** The ID of this position's direct manager. Null for top-level roles (e.g., CEO). */
  managerId: string | null;
  /** The type of role, either 'billable' (generates revenue) or 'nonBillable' (support/overhead). */
  roleType: 'billable' | 'nonBillable';

  // --- Calculated Financial Metrics (derived from above inputs) ---
  /** The total annual cost including salary plus benefits/taxes (salary * benefitsMultiplier). */
  totalSalary: number;
  /** The annual overhead cost attributed to this position (totalSalary * overheadMultiplier). */
  overheadCost: number;
  /** The combined total cost of this position (totalSalary + overheadCost). */
  totalCost: number;
  /** The annual revenue generated by this position (rate * utilization * annualBillableHours). */
  revenue: number;
  /** The net profit/loss for this position (revenue - totalCost). */
  profit: number;
  /** The profit margin as a percentage for this position (profit / revenue * 100). */
  margin: number;
}

/**
 * @interface PositionInput
 * @description Represents the data required to create a new position.
 * It omits the `id` and calculated financial metrics.
 */
export type PositionInput = Omit<Position, 'id' | 'totalSalary' | 'overheadCost' | 'totalCost' | 'revenue' | 'profit' | 'margin'>;

/**
 * @interface PositionUpdate
 * @description Represents the data required to update an existing position.
 * It includes the `id` and any fields that can be modified, omitting calculated metrics.
 */
export type PositionUpdate = Partial<Omit<Position, 'totalSalary' | 'overheadCost' | 'totalCost' | 'revenue' | 'profit' | 'margin'>> & Pick<Position, 'id'>;


/**
 * @interface AIAnalysisResult
 * @description Defines the structure of the AI-generated analysis output.
 */
export interface AIAnalysisResult {
  /** A list of positive aspects identified in the organizational structure. */
  strengths: string[];
  /** A list of potential risks, challenges, or growth opportunities. */
  risks_opportunities: string[];
  /** A list of general observations about the team structure or financials. */
  key_observations: string[];
}

/**
 * @interface TreeNode
 * @description Extends the Position interface to include properties
 * necessary for tree-like data structures (e.g., for OrgChart).
 */
export interface TreeNode extends Position {
  /** The depth of the node in the hierarchical tree, with the root at depth 0. */
  depth: number;
  /** An array of child nodes (direct reports) for this position. */
  children: TreeNode[];
}